JWT_APP_KEY=MDE5ZTgxZmQtZmE0OC03MzU4LTlkYzEtOWI4NTgxYjljZjI1LTAxOWU4MWZkLWZhNDgtN2RkMi1iOTViLWMxY2I5ZmZiYWMxNw==
JWT_EXPIRATION=6000000

H2_DATABASE=test-db
H2_USERNAME=sa
H2_PASSWORD=

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_TIMEOUT=3000ms
REDIS_POOL_MAX_ACTIVE=10
REDIS_POOL_MAX_IDLE=5
REDIS_POOL_MIN_IDLE=2

MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_DATABASE=blog
MYSQL_USERNAME=root
MYSQL_PASSWORD=1234

JPA_DDL_AUTO=create

AI_JOB_QUEUE_KEY=ai:job:queue
AI_JOB_QUEUE_PREFIX=ai:job:
AI_JOB_QUEUE_TTL=3600
AI_JOB_WORKER_DELAY=1000

AI_MODEL_URL=http://localhost:8000
AI_MODEL_ENDPOINT=/members
AI_MODEL_TIMEOUT=5s